// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTB4jIOXZFvlFv2O_sNZ-6k8bDfK_bilo',
    appId: '1:288565959399:android:b09eabb43625d5743be042',
    messagingSenderId: '288565959399',
    projectId: 'shopping-cart-30d97',
    storageBucket: 'shopping-cart-30d97.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCn1barPREvM4Zy_T5KIGj3hvh3x-T51NU',
    appId: '1:288565959399:ios:0317c114637996333be042',
    messagingSenderId: '288565959399',
    projectId: 'shopping-cart-30d97',
    storageBucket: 'shopping-cart-30d97.appspot.com',
    iosClientId: '288565959399-seckff15e61r0tngfl5f4869rvo15466.apps.googleusercontent.com',
    iosBundleId: 'com.hazey',
  );
}
